# Generated by Django 5.2.6 on 2025-11-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_comment_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
