# Generated by Django 5.2.6 on 2025-11-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_verified',
        ),
    ]
