# Generated by Django 5.2.6 on 2025-11-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_remove_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
