# Generated by Django 5.2.6 on 2025-11-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
