# Generated by Django 5.2.8 on 2025-11-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
